##
## Makefile for Makefile in /home/maires_b/Dropbox/PSU_2015_minitalk
##
## Made by Mairesse Baptiste
## Login   <maires_b@epitech.net>
##
## Started on  Mon Feb  1 09:40:34 2016 Mairesse Baptiste
## Last update Mon Feb  1 09:41:14 2016 Mairesse Baptiste
##
NAME		=	check_tetrimino

FLAG		=	-Wall -Wextra -W -ansi -pedantic

SRC			=	main.c \
					aff.c


all:
		gcc $(SRC) libmy.a -o $(NAME) $(FLAG)
clean:

fclean:		clean
		rm -f $(NAME)
re:		fclean all
